config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'site#splash'
  devise_for :users

  authenticate :user do
    get '/pens' => 'pens#index'
    get '/pens/:id' => 'pens#profile', as: 'profile'

    resources :locations
    resources :interests
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interest.rb
class Interest < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [
                                        :first_name,
                                        :middle_name,
                                        :last_name
                                      ])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: [
                                        :first_name,
                                        :middle_name,
                                        :last_name
                                      ])
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :set_interest, only: [:show, :edit, :update, :destroy]

  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
  end

  # GET /interests/new
  def new
    @interest = Interest.new
  end

  # GET /interests/1/edit
  def edit
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(interest_params)

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render :show, status: :created, location: @interest }
      else
        format.html { render :new }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interests/1
  # PATCH/PUT /interests/1.json
  def update
    respond_to do |format|
      if @interest.update(interest_params)
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @interest }
      else
        format.html { render :edit }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest.destroy
    respond_to do |format|
      format.html { redirect_to interests_url, notice: 'Interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest
      @interest = Interest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_params
      params.require(:interest).permit(:name, :level)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:city, :country, :state)
    end
end

app/controllers/pens_controller.rb
class PensController < ApplicationController
  def index
    @users = User.all
  end

  def profile
    @user = User.find(params[:id])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def splash
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/interests/_form.html.erb
<%= form_with(model: interest, local: true) do |form| %>
  <% if interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :interest_name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level, id: :interest_level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interests/edit.html.erb
<h1>Editing Interest</h1>

<%= render 'form', interest: @interest %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

app/views/interests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interests.each do |interest| %>
      <tr>
        <td><%= interest.name %></td>
        <td><%= interest.level %></td>
        <td><%= link_to 'Show', interest %></td>
        <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
        <td><%= link_to 'Destroy', interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interest', new_interest_path %>

app/views/interests/new.html.erb
<h1>New Interest</h1>

<%= render 'form', interest: @interest %>

<%= link_to 'Back', interests_path %>

app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @interest.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @interest.level %>
</p>

<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav" >
      <%= link_to 'Home', root_path, :class => 'nav-item nav-link' %>

        <% if current_user %>
          <%= link_to 'Profile', profile_path(current_user), :class => 'nav-item nav-link' %>
          <%= link_to 'Edit Interests', interests_path, :class => 'nav-item nav-link' %>
					<%= link_to 'Edit Account', edit_user_registration_path, :class => 'nav-item nav-link' %>
					<%= link_to "Sign out", destroy_user_session_path, :class => 'nav-item nav-link', :method => :delete %>
				<% else %>
					<%= link_to'Sign in', new_user_session_path, :class => 'nav-item nav-link' %>
					<%= link_to'Sign up', new_user_registration_path, :class => 'nav-item nav-link' %>
				<% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Penme</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= flash_messages %>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :location_city %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :location_country %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :location_state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Country</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.city %></td>
        <td><%= location.country %></td>
        <td><%= location.state %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @location.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @location.state %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/pens/index.html.erb
<div class="row">
  <div class="col-6 offset-sm-3">
    <h1 class="my-4 mx-auto text-center">Eligible Pen Pals</h1>
  </div>
</div>


<% @users.each do |user| %>
  <%= link_to pen_profile_path user do %>
    <div>
      <%= image_tag avatar_url(user) %>
      <%= "#{user.first_name} #{user.last_name[0].capitalize}." %>
    </div>
  <% end %>
<% end %>

app/views/pens/profile.html.erb
<%= @user.first_name %>

app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/splash.html.erb
<h1>Site#splash</h1>
<p>Find me in app/views/site/splash.html.erb</p>